version: '3'

services:
  pypcapkit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["bash", "/pypcapkit/docker/docker.sh"]
    container_name: pypcapkit
    image: pypcapkit
    volumes:
      - ../dist:/pypcapkit/dist
